### ISSUE TITLE
Permission to adapt for course I'm teaching?

### ISSUE THREAD

**Issue by zcline91** [buruzaemon/IntroductionToProbabilityPy#1]
Hi! I'm teaching a Probability course in the Spring, and had the idea of using the R simulations from Blitzstein and Hwang's book, but in a Jupyter notebook on Google Colab. Before adapting the code myself, I figured I'd check to see if anybody had done so already and found your repo. I noticed there's no license though, so I want to get permission before proceeding. May I adapt these notebooks you've created for use in my course?

**Comment by buruzaemon** [comment]
Thanks for reaching out to me, @zcline91. I actually wrote these notebooks for Prof. Blitzstein himself, with his approval provided that I put on each page / notebook mention of the Blitzstein & Hwang publication upon which these are based. That is why there is no license. I suggest you reach out to Prof. Blitzstein on Twitter (@stat110) and check with him if it is OK to use these notebooks for your course.

**Comment by zcline91** [comment]
Ah okay, that makes sense. Thank you very much for the information. I'll reach out to him and see what he thinks. Best wishes, and happy holidays!
